#!/bin/bash
set -eo pipefail

[ -d /sync ] || mkdir -vp /sync
chown -R nobody:nobody /sync

exec gosu nobody:nobody \
  /usr/local/bin/btsync --nodaemon --config /btsync.conf --log /dev/stdout
exit 0
